Fixed importing FieldDoesNotExist exception class for Django==3.1
paulocheque/django-dynamic-fixture pull request #134
Opened 2020-08-06 11:36 UTC by DrMartiner

2020-08-27 11:21 UTC, uhurusurfa commented
@paulocheque - adding to the requests above. Great app you have built and would be good to get this merged.

2020-09-06 00:30 UTC, jayvdb approved these changes

2020-09-10 06:44 UTC, pkasemir approved these changes
Please merge this, it would be great to use with Django 3.1+

2020-09-10 06:45 UTC, pkasemir commented
@paulocheque Can you merge this?

2020-09-29 22:42 UTC, clearyusc commented
Please merge!

2020-10-02 02:31 UTC, s-i-l-k-e commented
@paulocheque how is this progressing?

2020-10-02 08:38 UTC, uhurusurfa commented
Anyone interested in being a member  on a fork of this project until such time as Paulo decides to allow more developers to help him so that this type of scenario does not happen again?
That way we can provide timely solutions as  Django evolves and not stall other projects that use this one.
If and when Paulo decides to actively develop this app with more (trusted) people allowed to review and merge code fixes thus eliminating the scenario we find ourselves in then we can merge back in?

2020-10-02 11:09 UTC, RaddishIoW commented
I'm up for helping on the fork. This is preventing me from updating to 3.1 - the only thing preventing me from updating.

2020-10-02 11:39 UTC, RaddishIoW commented
@paulocheque committed a change to the Readme 10 days ago, so he's definitely still active on the project. Just a shame he hasn't approved this pull request yet. He might not have seen it I guess, but maybe he needs some other people approved to help out on GitHub?

2020-10-02 12:38 UTC, jheld commented
While at it, can you open an issue for PyPI ownership transfer? It may take some time, but since he has been uncommunicative despite some recent activity, having a fork and PyPI will make this seamless for users long-term.

@paulocheque We understand, life gets busy, all sorts of things happen (and we appreciate the work you have done); but making changes while ignoring critical updates provided by the community, do leave some folks with frustration.

2020-10-13 23:59 UTC, iamjstates commented
Merging this would be greatly appreciated

2020-10-14 06:44 UTC, JanMalte requested changes

2020-10-14 06:44 UTC, JanMalte commented on django_dynamic_fixture/django_helper.py
> +try:
I would suggest to remove the try/except block and only import from `django.core.exceptions`, as the exception was moved there 6 years ago. Only the legacy reference in `django.db.models.fields` was widely used and is removed with the 3.1 release.

2020-11-06 16:59 UTC, vecchp commented
Hi, this issue is also showing up as a blocker for https://github.com/saxix/django-adminactions/pull/173.  Any way we can move this forward?

2020-11-06 23:14 UTC, jheld commented
You can open up an issue for PyPI ownership.

2020-11-18 01:03 UTC, merged

2020-11-18 01:05 UTC, paulocheque commented
Hello guys, I am sorry for the delay, I will puy you guys as collaborators of the project ok?

2020-11-18 01:12 UTC, paulocheque commented
Version 3.1.1. released with this PR!

2020-11-18 15:49 UTC, RaddishIoW commented
@paulocheque Thank you for this - I (and I'm sure everyone else) appreciate the work you've done on this project. Thanks for making me a collaborator. I'll help out as I can, even if it's just keeping an eye out on GitHub for things like this.